#!/bin/bash

source $HOME/.config/hypr/start_scripts/scripts/functions
set -euo pipefail

notify-brightness() {
  local brightness="$1" 
  
  if [[ $((brightness)) -gt 50 ]]; then
    # brightness_icon=/home/rafa/.local/share/icons/awesome-wm-widgets-master/
    brightness_icon=~/.local/share/icons/Icons/brightness-4_117071.png
  elif [[ $((brightness)) -eq 50 ]]; then
    brightness_icon=~/.local/share/icons/Icons/brightness-medium_117265.ico
  elif [[ $((brightness)) -lt 50 ]]; then
    brightness_icon=~/.local/share/icons/Icons/brightness-5_117070.png
  fi
  # notify-send -u low "Brillo" "Nivel: ${brightness}%" -i $brightness_icon
  send_notification "Brillo" "Nivel: ${brightness}%" $brightness_icon
}

calc_poc_brightnes() {
  # Calculamos el porcentaje del brillo dado el valor actual y el valor total

  brightnessctl set $1 # Aumentamos o disminuimos en 5 el brillo
  local brightness=$(brightnessctl get | tr -dc '0-9') # Obtener el brillo actual
  local total_brightness=$(brightnessctl max | tr -dc '0-9') # Brillo total 
  local porc_brightnes=0

  # Calcular el porcentaje de brillo
  if [ $brightness -ne 0 ]; then
    porc_brightnes=$(echo "scale=2; $brightness/$total_brightness" | bc) # Calculando la razon entre el valore del brillo actual y el maximo valor
    porc_brightnes=$(echo "scale=0; $porc_brightnes * 100 / 1" | bc) # Calculando el porcentaje
  else
    porc_brightnes=0
  fi

  # Enviar o actualizar la notificación
  # notify-send --expire-time=1000 -u low -r 12345 "Brillo" "Nivel: $porc_brightnes%" -i ~/.local/share/icons/Icons/brightness-5_117070.png
  notify-brightness $porc_brightnes
}

iod="${1:2}" # flag para saber si vamos a incrementar o decrementar
brightnessctl -n 2880

case "$iod" in 
  inc) calc_poc_brightnes +5% ;;
  dec) calc_poc_brightnes 5%- ;;
  *) echo "Parametro no valido"; exit 1 ;;
esac
