#!/bin/bash

source $HOME/.config/hypr/start_scripts/scripts/functions
read_previous_config

themes_dir="$HOME/.config/colors"

listThemes=()

for theme_file in "$themes_dir"/*.json; do
  if [ -f "$theme_file" ]; then
    theme_name=$(basename "$theme_file" .json)
    listThemes+=("$theme_name")
  fi
done

listThemesString=$(printf "%s\n" "${listThemes[@]}")

choice=$(echo -e "$listThemesString" | rofi -dmenu -i -replace -config $HOME/.config/rofi/colors_themes.rasi "Seleccione un tema:")

if [ "$choice" ]; then
  # notify-send "Tema" "Estableciendo tema $choice"
  echo "$choice"
  $HOME/.config/hypr/start_scripts/scripts/statusbar --reload "$THEME_BAR" "$choice" "$POSITION"
fi
