#!/bin/bash

source $HOME/.config/hypr/start_scripts/scripts/functions
read_previous_config

# ----------------------------------------------------- 
# Carpeta de Temas
# ----------------------------------------------------- 
themes_path="$HOME/.config/hypr/waybar"

# ----------------------------------------------------- 
# Inicializar Arreglos
# ----------------------------------------------------- 
listThemes=()
listNames=""

# ----------------------------------------------------- 
# Leer carpeta de temas
# ----------------------------------------------------- 
for theme in "$themes_path"/*; do
  if [[ -d "$theme" ]]; then  # Verifica si es un directorio
    listThemes+=("$(basename "$theme")")
  fi
done

# ----------------------------------------------------- 
# Mostrar ventana de Rofi
# ----------------------------------------------------- 
listNames=$(printf "%s\n" "${listThemes[@]}")
choice=$(echo -e "$listNames" | rofi -dmenu -i -replace -config $HOME/.config/rofi/colors_themes.rasi "Seleccione un tema:")

# ----------------------------------------------------- 
# Elegir nuevo tema escribiendo la selección en ~/.cache/.themestyle.sh
# ----------------------------------------------------- 
if [ "$choice" ]; then
  echo "$choice"
  $HOME/.config/hypr/start_scripts/scripts/statusbar --reload "--$choice" "$COLOR" "$POSITION"
fi

