#!/bin/bash

#wallpaper fetcher and wallpaper rotator
#type "var" in a terminal to change settings - example
#variety &

SCRIPTSDIR=$HOME/.config/hypr/start_scripts/scripts

# Kill already running process
_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof ${_prs}) ]]; then
		killall -9 ${_prs}
	fi
done

# Apply themes
#${SCRIPTSDIR}/gtkthemes &

# Lauch notification daemon (mako)
#${SCRIPTSDIR}/notifications &

${SCRIPTSDIR}/statusbar &  # Lauch statusbar (waybar)

# Xauthority
#${SCRIPTSDIR}/xauthority &

function run {
	if ! pgrep -x $(basename $1 | head -c 15) 1>/dev/null; then
		$@ &
	fi
}

waypaper --backend swaybg --restore # Set last wallpaper
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
run nm-applet & # Network manager
# numlockx on &
