#!/bin/bash

SCRIPTSDIR=$HOME/.config/hypr/start_scripts/scripts

# Kill already running process
_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof ${_prs}) ]]; then
		killall -9 ${_prs}
	fi
done

function run {
	if ! pgrep -x $(basename $1 | head -c 15) 1>/dev/null; then
		$@ &
	fi
}

waypaper --backend swaybg --restore & # Set last wallpaper
${SCRIPTSDIR}/statusbar --save_ok  # Lauch statusbar (waybar)
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
run nm-applet & # Network manager
run avizo-service & # Volume and notify deamon
run blueman-applet & # systray app for Bluetooth
# numlockx on &
