#!/bin/bash

source $HOME/.config/hypr/start_scripts/scripts/functions
set -euo pipefail

iod="${1:2}" # Tomar un parametro para saber si vamos a aumentar o disminuir el volumen

notify_volume() {
  local volume="$1" 
  if [[ $((volume)) -ge 50 ]]; then
    volume_icon=/home/rafa/.local/share/icons/awesome-wm-widgets-master/volume-widget/icons/audio-volume-high-symbolic.svg
  elif [[ $((volume)) -eq 0 ]]; then
    volume_icon=/home/rafa/.local/share/icons/awesome-wm-widgets-master/volume-widget/icons/audio-volume-muted-symbolic.svg
  elif [[ $((volume)) -lt 50 ]]; then
    volume_icon=/home/rafa/.local/share/icons/awesome-wm-widgets-master/volume-widget/icons/audio-volume-low-symbolic.svg
  fi

  send_notification "Volumen" "Nivel: ${volume}%" "$volume_icon"
}

set_print_vol() {
  local action="$1"
  local current_volume=$(pamixer --get-volume)

  if [[ $action == "-t" ]]; then
    pamixer $action  # Intercambiamos modos entre mute o unmute

    is_mute=$(pamixer --get-mute) # Veirficamos si esta mute o no
    if [[ $is_mute == true ]]; then
      current_volume="0"
    fi

    notify_volume "$current_volume" $2 
    return
  fi

  current_volume=$(pamixer "$action" 5 --get-volume)
  notify_volume "$current_volume" $2
}

case "$iod" in 
  inc) set_print_vol -i low ;;
  dec) set_print_vol -d low ;;
  mute)set_print_vol -t low ;;
  *) echo "Parametro no valido"; exit 1 ;;
esac
