keymap_set({
  { 'i',          'jj',            '<esc>',                                           { desc = "go to normal mode" } },
  { 'i',          'JJ',            '<ESC>',                                           { desc = "Go to normal mode" } },
  { 'n',          '<leader>w',     cmd 'write',                                       { desc = 'Save' } },
  { 'n',          '<leader>q',     cmd 'quit',                                        { desc = 'Leave' } },
  { 'n',          '<leader><S-q>', cmd 'bufdo bd|qa',                                 { noremap = true, desc = "Close all buffers" } },
  { { 'n', 'x' }, 'cp',            '"+y',                                             { desc = "Copy select text" } },
  { { 'n', 'x' }, 'cv',            '"+p',                                             { desc = "Past the copy text" } },
  { { 'n', 'x' }, 'x',             '"_x',                                             { desc = "Cut select text" } },
  { 'n',          '<leader>a',     cmd 'keepjumps normal! ggVG',                      { desc = "Select all" } },
  { 'n',          '<leader>j',     '*``cgn',                                          { desc = "Delete word, and search it" } },
  { 'n',          '+',             '<C-a>',                                           { desc = "Sum" } },
  { 'n',          '-',             '<C-x>',                                           { desc = "Sub" } },
  { 'n',          'dw',            'vb"_d',                                           { desc = "Visual delete to blackhole" } },
  { 'n',          'ss',            cmd 'split<Return><C-w>w',                         { desc = "Split horizontal window" } },
  { 'n',          'sv',            cmd 'vsplit<Return><C-w>w',                        { desc = "Split vertical window" } },
  { 'n',          '<leader>nh',    cmd 'nohlsearch',                                  { noremap = true, silent = true, desc = 'Clear search highlight' } },
  { '',           'sh',            '<C-w>h',                                          { desc = "Move cursor to left window" } },
  { '',           'sk',            '<C-w>k',                                          { desc = "Move cursor to up window" } },
  { '',           'sj',            '<C-w>j',                                          { desc = "Move cursor to down window" } },
  { '',           'sl',            '<C-w>l',                                          { desc = "Move cursor to right window" } },
  { 'n',          '<C-w><left>',   '<C-w><',                                          { desc = "Resize window left" } },
  { 'n',          '<C-w><right>',  '<C-w>>',                                          { desc = "Resize window right" } },
  { 'n',          '<C-w><up>',     '<C-w>+',                                          { desc = "Resize window up" } },
  { 'n',          '<C-w><down>',   '<C-w>-',                                          { desc = "Resize window down" } },
  { 'v',          '>',             '>gv',                                             { desc = 'after tab in re-select the same' } },
  { 'v',          '<',             '<gv',                                             { desc = 'after tab out re-select the same' } },
  { 'n',          'n',             'nzzzv',                                           { desc = 'Goes to the next result on the search and put the cursor in the middle' } },
  { 'n',          'N',             'Nzzzv',                                           { desc = 'Goes to the prev result on the search and put the cursor in the middle' } },
  { "n",          "gj",            [[/^##\+ .*<CR>]],                                 { buffer = true, silent = true, desc = "Go to down markdown header" } },
  { "n",          "gk",            [[?^##\+ .*<CR>]],                                 { buffer = true, silent = true } },
  { 'n',          '<leader>nd',    cmd 'NoiceDismiss',                                { desc = 'Dismiss Noice Message' } },
  { 'n',          '<C-w>z',        cmd 'WindowsMaximize',                             { desc = "Set maximun size to current window" } },
  { 'n',          '<C-w>>',        cmd 'WindowsMaximizeVertically',                   { desc = "Set maximum vertical size to current window" } },
  { 'n',          '<C-w>^',        cmd 'WindowsMaximizeHorizontally',                 { desc = "Set maximum horizontal size to current window" } },
  { 'n',          '<C-w>=',        cmd 'WindowsEqualize',                             { desc = "Set equal size to all window" } },
  { 'n',          '<leader>spl',   function() vim.o.spell = not vim.o.spell end,      { desc = "Active spell check" } },
  { 'n',          '<leader>dr',    function() require("dap").continue() end,          { noremap = true, silent = true } },
  { 'n',          '<leader>dq',    function() require("dap").close() end,             { noremap = true, silent = true } },
  { 'n',          '<leader>db',    function() require("dap").toggle_breakpoint() end, { noremap = true, silent = true } }
})
